### ISSUE TITLE
use scoped_refptr to create containter may cause segmentation fault on ubuntu16.04

### ISSUE THREAD

**Issue by sunbingfengPI** [yue/yue#10]
## environment:

ubuntu 16.04

## issue description

ref-counted container may cause segmentation fault if setting on_draw event.

## sample code
```
  scoped_refptr<nu::Container> radarView = new nu::Container;
  radarView->SetStyle("position", "absolute", "width", radar_view_size, "height", radar_view_size, "top", 0, "right", 0);
  radarView->on_draw.Connect([&](nu::Container* self, nu::Painter* painter, const nu::RectF& dirty){
    std::cout << "container on_draw on rect: " << self->GetBounds().ToString() << std::endl;
    scoped_refptr<nu::Canvas> temp_canvas = new nu::Canvas(nu::SizeF(radar_view_size, radar_view_size), 1.0f);
    nu::RectF bounds = self->GetBounds();
    painter->DrawCanvas(temp_canvas.get(), nu::RectF(0, 0, bounds.width(), bounds.height()));
  });
```

**Comment by sunbingfengPI** [comment]
on_draw function called with wrong self&&painter pointer, maybe something goes wrong.

**Comment by zcbenz** [comment]
Can you provide a full example? I tried to insert your code in the sample app but could not reproduce.

**Comment by sunbingfengPI** [comment]
@zcbenz it works well on mac, but fails on ubuntu. Above code snippet could definitely reproduce.

**Comment by zcbenz** [comment]
It would be great if you can provide a full file that I can just compile, the crash may be related to how you show the window and how you add the `radarView` to the window.

**Comment by zcbenz** [comment]
Closing until we have a fully reproducible example.

**Comment by sunbingfengPI** [comment]
@zcbenz I tested using latest v0.3.0, it runs well. 

thanks
