### ISSUE TITLE
Browser view can't receive mouse event

### ISSUE THREAD

**Issue by MissinA** [yue/yue#105]
Browser view can't receive the mouse to click and move events, set the same browser: setmousedowncanmovewindow (can) not to take effect.
What am I going to do to implement a titlebar imitation in HTML in the Borderless window
Note: My system is Win10

**Comment by zcbenz** [comment]
This is unfortunately impossible with system WebView, which has its own routines for handling input events and would break if we install custom mouse/key event handles.
