### ISSUE TITLE
Cannot use mac menubar 

### ISSUE THREAD

**Issue by johnsusek** [yue/yue#107]
First of all, thank you for this awesome library! Do you have a patreon or github sponsorship option for this project I can contribute to? You should set one up if not!

Here is the bug:

Steps to reproduce:

- Run muban example app (or any other yue app) under Mac OSX
- Try to click menubar, note you cannot click items
- Switch to another app, then back to muban
- Note you can now click the menubar

I am on Mac OSX 10.15 in case that matters.
Yode v14.2.0

I've tried things in code like deactivating and activating the window, hiding/showing the window, nothing seems to help. Only if you switch to another app, then back to a yue app does the menubar start working.

Let me know if you need any other info or if you can think of a workaround. Thanks!

**Comment by johnsusek** [comment]
This may be hepful:

https://stackoverflow.com/questions/33345686/cocoa-application-menu-bar-not-clickable

**Comment by johnsusek** [comment]
There is this note at the above link:

> I fixed by removing LSUIElement in Info.plist if the app has a Window and Menu Bar.
> The old solution is that we override this config with [NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];, but in Catalina, it doesn't work anymore.

I wonder if there is a way to modify the info.plist used for the app?

**Comment by gamelaster** [comment]
> I wonder if there is a way to modify the info.plist used for the app?
@johnsusek https://github.com/yue/node/blob/7fa8aef206d34e5984033e1af2baabdfe92b3bda/tools/gyp/pylib/gyp/generator/ninja.py#L875

**Comment by zcbenz** [comment]
This is an odd behavior of macOS when your app is not bundled, once you put your app in a `.app` bundle this behavior will be gone.

There are guides on how to do it manually:
https://stackoverflow.com/questions/1596945/building-osx-app-bundle

> Do you have a patreon or github sponsorship option for this project I can contribute to? You should set one up if not!

I have a full time job and I can only maintain this project on my part time, sometimes I may not work on it for months. So currently accepting sponsorship is probably not appropriate for me. But thank you for your kindness anyway!
