### ISSUE TITLE
Chromium Edge compatiblity

### ISSUE THREAD

**Issue by samad-aghaei** [yue/yue#108]
The most recent Windows 10 update has completely replaced Edge with Chromium, is yue still compatible with it?
If yes, it will use which libraries of them?

**Comment by Losses** [comment]
Related to #91 ?

**Comment by zcbenz** [comment]
Yeah it is compatible with Chromium Edge. According to Edge's document:

> The default channel search order is the WebView2 Runtime, Beta, Dev, and Canary. When there is an override WEBVIEW2_RELEASE_CHANNEL_PREFERENCE environment variable or applicable releaseChannelPreference registry value with the value of 1, the channel search order is reversed.
