### ISSUE TITLE
WebView2 not loaded

### ISSUE THREAD

**Issue by Gurkengewuerz** [yue/yue#109]
I tried to use the browser component on my windows 10 machine using the WebView2 but everytime only my Internet Explorer is used.
I am running `Microsoft Edge Version 86.0.622.68 (official build) (64-Bit)` on `Windows 20H2 (Build 19042.572)`.
The WebView2Loader.dll **copied** from `./node_modules/gui` is for the test inside the root project folder, out folder (to test also with packed .exe), still in node_modules/gui and also in system32 but still the the internet explorer is used.

To test which browser is used i am using https://www.whatismybrowser.com/.

My simple app is the following:
```js
const gui = require("gui");

class App {
  constructor() {
    this.win = gui.Window.create({
      frame: true,
    });
    this.win.setContentSize({ width: 400, height: 400 });
    this.win.onClose = () => gui.MessageLoop.quit();

    this.contentView = gui.Container.create();
    this.contentView.setStyle({ flexDirection: "row" });
    this.win.setContentView(this.contentView);

    this.browserView = gui.Browser.create({
      devtools: true,
      contextMenu: false,
      allowFileAccessFromFiles: true,
      hardwareAcceleration: false,
      webview2Support: true,
    });
    this.browserView.setStyle({ flex: 1 });
    this.browserView.loadURL("https://www.whatismybrowser.com/");
    this.contentView.addChildView(this.browserView);
  }

  start() {
    this.win.center();
    this.win.activate();
  }
}

module.exports = App;

```

Maybe you @zcbenz have some ideas? Do you have a debugging version to see where the native api is trying to search or to test if the chromium edge is somehow supported?

**Comment by Gurkengewuerz** [comment]
Update: If i install Edge Beta it works. Then i uninstalled the beta version and downloaded the newest chrome edge vesion from Microsoft (https://www.microsoft.com/en-us/edge). Still not working :/

**Comment by zcbenz** [comment]
It seems that now WebView2 does not support stable browser versions, please check: https://github.com/MicrosoftEdge/WebView2Feedback/issues/521#issuecomment-707223191.
