### ISSUE TITLE
Tray dissappears

### ISSUE THREAD

**Issue by mdings** [yue/yue#110]
This is probably a common issue related to garbage collections and process loops but I just can't recall the solution.

I have a tray as following:
```javascript
let tray = gui.Tray.createWithTitle(`My title`)
```

and I run the app with yode which I have installed under a npm script:
```
scripts: {
   start: "yode ./index.js"
}

npm start
```

However after a few secs the tray disappears again. That doesn't happen whenever I run the same script with `node ./index.js` and the process loop "hack":

```
if (!process.versions.yode) {
    gui.MessageLoop.run()
    process.exit(0)
}
```

What am I missing?

**Comment by mdings** [comment]
Hmmz just figured out that the app quits because of some error coming from an external dependency so not related to yue.
However I do find that my grap menu just freezes after a few seconds. Consider the example below:

```javascript
const gui = require('gui')
var tray = gui.Tray.createWithTitle(`My Title`)
var trayMenu = gui.Menu.create([{
    label: 'Label one',
    submenu: [{
        type: 'submenu',
        label: 'Click me',
        onClick() {
            console.log('righyy')
        }
    }]
}, {
    label: 'Quit',
    onClick() {
        process.exit(0)
    }
}])

tray.setMenu(trayMenu)
```

The click action which outputs to the console fires only a few times until the app freezes in a sense that click actions aren't fired at all anymore.

**Comment by zcbenz** [comment]
The tray had actually been garbage collected, but on macOS it persisted in the bar even though the object had been released (I will push a fix to make it disappear instead).

When running the script with Node, the program will block at `gui.MessageLoop.run()`, and all the local variables in the file will not be garbage collected until the function exits, i.e. when the program exits. When running with Yode they local variables will be garbage collected as usual.

The simplest way to fix it, is to change `var tray` to `global.tray`.

I'll add some documentations to make this behavior more clear.

**Comment by zcbenz** [comment]
Closed with https://github.com/yue/yue/commit/acd5be3df12ac90383a05bc523b3df72e34230e0.
