### ISSUE TITLE
The operating system cannot run node.gui

### ISSUE THREAD

**Issue by gamelaster** [yue/yue#112]
Hello,

on my Win10, I have issues with running yue. When node package is trying to require `gui.node`, it returns this: `The operating system cannot run %1`. I checked literally everything, if I have VC Redist, I take look on it with Dependency Walker, but I didn't found anything useful why this happens. Any ideas?

**EDIT:** I tried older version, this problem happening after `Yue v0.9.2`, `Yue v0.9.1` works correctly.

Thanks

**Comment by zcbenz** [comment]
Thanks for reporting! This has been fixed with https://github.com/yue/yue/commit/07f33da1b70147fbe65c0de892ad940d76082816.
