### ISSUE TITLE
Label color

### ISSUE THREAD

**Issue by AsuraTS** [yue/yue#113]
Hello,

Label color are reset after setText().
Yue version: 0.9.4/0.9.5.

Example code:
```win.setContentView(contentView);
const gui = require('gui');

const win = gui.Window.create({});
win.setContentSize({width: 300, height: 200});

const contentView = gui.Container.create();
win.setContentView(contentView);

const label = gui.Label.create('Red label');
label.setColor('#FF0000');
contentView.addChildView(label);

label.setText('Black label');

win.center();
win.activate();
```

So, i expect the label color to be red after update text, but it black. On some previous versions it worked normal.

Upd: Font are reset too.

**Comment by zcbenz** [comment]
Fixed with 0c4999b5675febe1accbedbaace9d881639c4453.
