### ISSUE TITLE
support builds with mingw-w64

### ISSUE THREAD

**Issue by franko** [yue/yue#114]
I tried to compile Yue on Windows using gcc with mingw-w64 from msys2 but it fails. From what I understand Yue requires Microsoft Visual Studio to compile on Windows.

Is there any chance that building with mingw-w64 can be supported ?

**Comment by zcbenz** [comment]
Yue's source code depends on Chromium's base library, which can only be compiled with clang or VS 2019 on Windows, so unfortunately we can not provide support for mingw-w64.

**Comment by franko** [comment]
This is a little bit unfortunate as many free-software developers use mingw-w64 on Windows. In addition clang is readily available in the mingw environment using the msys2 packages.

I am wondering if there is any real obstacle to use mingw except the fact that the yue's cmake config uses visual studio compiler specific flags. I may try to change the flags myself and check if it can compile.
