### ISSUE TITLE
Deno support?

### ISSUE THREAD

**Issue by sample-text-here** [yue/yue#115]
Are there plans to support deno? I think supporting it would be great, currently there are not many gui libraries for deno and the ones I've found aren't good.

I know this may be a lot of work, but it would be extremely appreciated if you could do this.

**Comment by zcbenz** [comment]
The native plugin of deno requires using rust-lang, so at current stage it unrealistic to support deno in yue.

Things would be much easier if deno could allow writing native plugins with C++, in which case all of all existing V8 bindings code could just be reused. But I think it is probably never going to happen.

**Comment by sample-text-here** [comment]
oh, ok

**Comment by harsha7addanki** [comment]
Deno ffi supports c++ for foreign functions see https://deno.land/manual/runtime/ffi_api#foreign-function-interface-api for all supported languages
