### ISSUE TITLE
Ordinal 345

### ISSUE THREAD

**Issue by KevinMagnifico260** [yue/yue#116]
![yue-issue-dll](https://user-images.githubusercontent.com/55334636/108249305-c5140500-7109-11eb-9133-3a821a919daf.PNG)

Did you know how to fix these problem sir/mam

**Comment by zcbenz** [comment]
The official `lua53.exe` does not have necessary [manifest file](https://github.com/yue/yode/blob/master/src/yode.exe.manifest) defined in it, so errors like this will happen when using certain components.

I'll see if I can solve this problem in our dll binaries, if not we might have to provide our own `lua53.exe` distributions.

**Comment by kkocdko** [comment]
> The official `lua53.exe` does not have necessary [manifest file](https://github.com/yue/yode/blob/master/src/yode.exe.manifest) defined in it, so errors like this will happen when using certain components.
> 
> I'll see if I can solve this problem in our dll binaries, if not we might have to provide our own `lua53.exe` distributions.

May not a bug? Just use `wlua53.exe` on windows, I have tried.

**Comment by KevinMagnifico260** [comment]
many thanks kkocdko

**Comment by zcbenz** [comment]
Closed with https://github.com/yue/yue/commit/f25bb4720107f65e042ad0bd74896d989dbf2358.
