### ISSUE TITLE
mouse click modifiers (CTRL, ALT, SHIFT) 

### ISSUE THREAD

**Issue by tacoberu** [yue/yue#117]
Yue Version: lua, 0.9.6
Operating System: linux

Hi.
Would it be possible to add support for event details? 
For example, I would need to distinguish between right-clicking and left-clicking on a button, label, entry, etc. And if I held CTRL with it.

**Comment by zcbenz** [comment]
You can use the methods of [`Event` class](https://libyue.com/docs/latest/lua/api/event.html):

```lua
print(gui.Event.isshiftpressed())
```

Also when handling the mouse and keyboard events, the passed `event` argument's `modifiers` property can be used to test the modifier keys.
