### ISSUE TITLE
is building for electron supported ?

### ISSUE THREAD

**Issue by sen0rxol0** [yue/yue#118]
As seen in this repo https://github.com/zcbenz/electron_yue.
Or can i at least get a description on how to do it ?
Thank you.

Operating System: macOS

**Comment by zcbenz** [comment]
No it is not really supported now, recent versions of Electron require the native modules to be built with certain versions of libc++, so providing prebuilt binaries are not going to work well.

My plan is to restructure the node module's code so it builds from source code when installing from npm, which should be able to solve future compatibility issues.

**Comment by zikosichi** [comment]
Hi @zcbenz,

Do you have any estimations on this? Or could you give some hints on how to compile it for electron 13 manually before restructuring the node module's code?

`gui.node` with electron runtime builds without any issues, but when I import it in the project I get the following error:
`/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV`

Which is probably related to `libc++`

**Comment by zcbenz** [comment]
I might be able to have a try 2 months later, but there is no guarantee on it.

With current build settings I don't think there is an easy way to build for Electron.

**Comment by zcbenz** [comment]
Closed with 091d19a.
