### ISSUE TITLE
APIs for controlling scroll position in Scroll view

### ISSUE THREAD

**Issue by tezlm** [yue/yue#119]
```cpp
void SetScrollPosition(double x, double y);
std::tuple<double, double> GetScrollPosition() const;
Signal<bool(View*, const ScrollEvent&)> on_scroll;
struct ScrollEvent : public Event {
  PointF position;
};
```

dynamically loading content is annoying, resizing a Scroll automatically scrolls to the top. this would let you preserve the scroll position when new content is added to a container + scroll. `on_scroll` could allow for lazily loading content. this would also allow for better View focusing (eg. jump/scroll to view on click)

**Comment by zcbenz** [comment]
Fixed with https://github.com/yue/yue/commit/995679a30f7b9114bc354ace374d55fe00212aaa.
