### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by zikosichi** [yue/yue#121]
Yue Version: 0.9.6
Operating System: MacOS Big Sur

Trying to build `node_yue` target but getting the following error after running `build.js`:

```
error: definition of implicit copy assignment operator for 'Location' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
  Location(const Location& other);
```

![image](https://user-images.githubusercontent.com/16005795/123309290-06d41280-d525-11eb-9d3b-1c4bdd8c1307.png)

Any help would be hugely appreciated.

**Comment by zcbenz** [comment]
Fixed with https://github.com/yue/build-gn/commit/1ec9140f2159feb4bf08353773997e4564e417b4 and https://github.com/yue/yue/commit/8e38bfd834cbfe509606e1257e1df25c9897e0bc.
