### ISSUE TITLE
libyue_v0.9.7_mac.zip build fail

### ISSUE THREAD

**Issue by zzj1213** [yue/yue#122]
Yue Version: libyue_v0.9.7_mac.zip
Operating System: macOS Big Sur 11.5.1

mkdir build
cd build
cmake ..
make

give the following errors:

/Users/mac/git/js/yue/out/dist/libyue_v0.9.7_mac/src/mac/base/base_jumbo_7.cc:4428:17: error: static_assert expression is not an integral constant expression
  static_assert(PAGE_SIZE % 1024 == 0, "Invalid page size");
                ^~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/mach/i386/vm_param.h:110:33: note: expanded from macro 'PAGE_SIZE'
#define PAGE_SIZE               vm_page_size
                                ^
/Users/mac/git/js/yue/out/dist/libyue_v0.9.7_mac/src/mac/base/base_jumbo_7.cc:4428:17: note: read of non-const variable 'vm_page_size' is not allowed in a constant expression
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/mach/i386/vm_param.h:110:33: note: expanded from macro 'PAGE_SIZE'
#define PAGE_SIZE               vm_page_size
                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/mach/vm_page_size.h:42:25: note: declared here
extern  vm_size_t       vm_page_size;

**Comment by wahern** [comment]
FWIW, looking at the system header a quick workaround should be setting MACOSX_DEPLOYMENT_TARGET to earlier than 10.16. Building for 10.14 works for me. I'm still using libyue 0.9.6 and the 11.1 SDK, but it looks like yue 0.9.6 would have the same issue if I wasn't declaring an older deployment target (-mmacosx-version-min=10.14).

Proper fix is probably to remove the preprocessor conditional in Yue.

**Comment by zcbenz** [comment]
Closed with 61777eb.
