### ISSUE TITLE
Can you add canvas instance to window or view?

### ISSUE THREAD

**Issue by MiccDev** [yue/yue#123]
Yue Version: 0.9.7
Operating System: Windows

How would you add a canvas to the window or a view?
Is there a function for it? I have been searching on the docs and I can not seem to find anything.

While I am here, does yue have a discord I could ask questions on?

Thanks!

**Comment by zcbenz** [comment]
The canvas can not be added to view directly, instead you should subscribe to the `on_draw` event of `Container` to copy the contents in canvas into the view. 

You can find an example at:
https://github.com/yue/yue-sample-apps/blob/master/drawing/lua/drawing.lua#L226
