### ISSUE TITLE
Disabling TextEdit NSScrollView elasticity and background

### ISSUE THREAD

**Issue by wahern** [yue/yue#124]
Yue Version: 0.9.6
Operating System: macOS

TextEdit widgets (NSTextView) support text selection and copying, unlike Label widgets. And unlike Entry (NSText) widgets, editing can be disabled without disabling text selection. In principle they're a simple, obvious choice for text that you want the user to be able to select and copy, at least on macOS. However, NSTextView is embedded within NSScrollView (reading the Yue code, NSTextView seems to be literally subclassed from NSScrollView). But other than exposing scrollbar policy, Yue doesn't expose methods for controlling other properties of NSScrollView. There are two significant deficiencies using NSTextView which cannot be worked around without API enhancements:

1) The parent NSScrollView is "elastic" by default. (At least on macOS 10.15 and 11.0, the default "automatic" elasticity policy enables elasticity.) If you drag the NSTextView overlay it moves, exposing the NSScrollView background. Elastic is similar (identical?) to "bounce" in the iOS SDK. See https://developer.apple.com/documentation/appkit/nsscrollview/1403540-horizontalscrollelasticity?language=objc and https://developer.apple.com/documentation/appkit/nsscrollview/1403475-verticalscrollelasticity?language=objc

2) TextEdit:setbackgroundcolor sets the NSTextView background, but not the NSScrollView. Reducing the alpha channel on NSTextView simply exposes the NSScrollView background, which seems to be defaulted to #FFFFFFFF. 

Two feature requests, in order of importance.

1) Fix the background discrepancy between NSTextView overlay and NSScrollView parent, either by a) propagating TextEdit::setbackgroundcolor to the NSScrollView parent, b) initializing NSScrollView alpha channel to 0 (transparent), or c) adding a TextEdit::setscrollbackgroundcolor method.

2) Fix the elasticity issue by a) disabling elasticity on the parent NSScrollView or b) adding TextEdit::setscrollelasticity()

I'd be happy to submit patches for the above, but would like to know which approaches are preferred. Though, I'm using the Lua bindings, can only compile the Lua bindings, and can't test JavaScript/Node.js bindings.

**Comment by zcbenz** [comment]
Thanks for the detailed explanations!

On the feature requests,

> 1\. Fix the background discrepancy between NSTextView overlay and NSScrollView parent, either by a) propagating TextEdit::setbackgroundcolor to the NSScrollView parent, b) initializing NSScrollView alpha channel to 0 (transparent), or c) adding a TextEdit::setscrollbackgroundcolor method.

I prefer making the `NSScrollView` transparent.

> 2\. Fix the elasticity issue by a) disabling elasticity on the parent NSScrollView or b) adding TextEdit::setscrollelasticity()

I prefer adding `SetScrollElasticity` method to `TextEdit` and `Scroll`, since some use cases want the elasticity effect.

**Comment by wahern** [comment]
Done: https://github.com/yue/yue/pull/126

**Comment by zcbenz** [comment]
Closed with #126.
