### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by rubyFeedback** [yue/yue#125]
Would it be possible to add screenshots on the main README? A bit similar
to libui.

Ideally a few different applications. Perhaps a range of 3-5 or something 
reasonable so people can just get a very quick first visual impression;
ideally even notice differences. Eyecandy works, IMO.

**Comment by rubyFeedback** [comment]
(Clarification: I meant 3-5 images or so, perhaps starting with a hello
world button and the last image may be some slightly larger
application, just to showcase what is doable in yue.)

**Comment by zcbenz** [comment]
Thanks for the advise, currently there are not much visual elements supported in libyue, so I prefer not putting screenshots in README for now. Users can find screenshots in the links under "Examples".
