### ISSUE TITLE
App crashes after 15s

### ISSUE THREAD

**Issue by mdings** [yue/yue#130]
Yue Version:  0.10.2
Operating System: MacOS Montery 12.1

My app crashes/disappears after 15s no matter what. Although it seems like a gc-issue, I think the app just errors out. Even for the simplest app, like the sample app below. Any idea what might be going on? Is there a way to get some more error logging? FWIW: I use a node script with yode to start the app: `yode .`

@update 1: terminal logs `segmentation fault`
@update 2: this only seems to happen when using yode and even after packaging the app with yackage (`yackage dist out`). So this seems to be yode-related. Running dev using `nodemon ./index.js` seems to mitigate the error. But that will leave me still stranded when packaging up the app for distribution..
@update 3: I'm reading into this [issue](https://github.com/yue/yode/issues/5) on the issue tracker for the yode repo which seems to be related and also seems to fix the error. I find it strange though, cause this never happened on previous apps before 🧐 
@update 4: Sorry for the spam 😀 

```
const gui = require('gui')

const win = gui.Window.create({})
win.onClose = () => gui.MessageLoop.quit()

const edit = gui.TextEdit.create()
edit.setStyle({flex: 1})
win.setContentView(edit)

// Calculate height for 1 and 20 lines.
edit.setText('1')
const minHeight = edit.getTextBounds().height
edit.setText('1' + '\n1'.repeat(19))
const maxHeight = edit.getTextBounds().height
edit.setText('')

// Automatically change window size for the text edit view.
edit.onTextChange = () => {
  let height = edit.getTextBounds().height
  if (height < minHeight)
    height = minHeight
  else if (height > maxHeight)
    height = maxHeight
  const size = win.getContentSize()
  if (height != size.height) {
    size.height = height
    win.setContentSize(size)
  }
}

win.setContentSize({width: 200, height: minHeight})
win.center()
win.activate()
edit.focus()

if (!process.versions.yode) {
  gui.MessageLoop.run()
  process.exit(0)
}
```

**Comment by zcbenz** [comment]
It is expected behavior to have the window disappeared after garbage collection, you can find how to solve it at https://libyue.com/docs/latest/js/guides/faq.html#window-disappears-after-some-time-when-using-yode-.

But it is a bug that the app crashed after garbage collection, and I should update the example apps' code.

**Comment by mdings** [comment]
No everything's is fine now! Just panicking over nothing really, haha 😀
