### ISSUE TITLE
Global shortcut support

### ISSUE THREAD

**Issue by mdings** [yue/yue#131]
Is there currently a way to support global shortcuts when the app is not active? I would like to be able to register a keyCombo that starts a part of the app when it's in the background. From what I can see in the docs this is currently not supported, right?

**Comment by zcbenz** [comment]
It is not currently supported, but there are some Node.js modules can be used: https://www.npmjs.com/package/hotcakey.

**Comment by mdings** [comment]
That works for me, thanks!
