### ISSUE TITLE
Lua in Windows does not work

### ISSUE THREAD

**Issue by stuta** [yue/yue#133]
Yue Version: lua_yue_lua_5.1_v0.10.2_win_x64.zip, lua_yue_lua_5.4_v0.10.2_win_x64
Operating System: Windows 10, Windows 11 arm64

.\lua.exe .\drawing.lua
C:\nc\nc-server\test\yue\lua.exe: error loading module 'yue.gui' from file 'C:\nc\nc-server\test\yue\yue.dll':
        The operating system cannot run %1.

This works in OSX but does not work in Windows with lua5.1, Luajit, or Lua 5.4. I also tried v0.10.1 and in Windows 11 arm64. Luajit was built with MinGW or native VS 2017. Both fail, always with the same error.

**Comment by zcbenz** [comment]
The arch of module must much the arch of Lua, it seems that you are trying to load x64 version of module on arm64 system, if that is the case you should use `lua_yue_lua_5.1_v0.10.2_win_arm64.zip` instead.

**Comment by stuta** [comment]
I tested this on an x64 machine with the correct Yue, the same error. This is the result of the Windows 11 arm (M1 Mac in Parallels).

./lua .\test.lua
C:\Users\test\lua.exe: error loading module 'yue.gui' from file '.\yue.dll':
        The operating system cannot run %1.
stack traceback:
        [C]: ?
        [C]: in function 'require'

yue.dll: PE32+ executable (DLL) (console) Aarch64, for MS Windows
WebView2Loader.dll: PE32+ executable (DLL) (console) Aarch64, for MS Windows
lua.exe: PE32+ executable (console) Aarch64, for MS Windows
lua51.dll: PE32+ executable (DLL) (GUI) Aarch64, for MS Windows
