### ISSUE TITLE
Multi select for Table and cell alignment bug

### ISSUE THREAD

**Issue by dickysyaputra** [yue/yue#144]
Yue Version: 0.11.0
Operating System: MacOS 12.4 Monterey

Can you add multi select for Table? I think this feature will really useful.

And i got this view when use Table, the cell is not centered well (aligned to top): https://prnt.sc/mL-L24Icxo31

This is great library, i hope development will continuously :)

**Comment by zcbenz** [comment]
Fixed with 8227dc22571fcafce137c58b8fe2fc6a693df5da and 54cd7d3e8138ef37cf7cd05005ba38c400ec39da.
