### ISSUE TITLE
How about use the TextAlign in the Label?

### ISSUE THREAD

**Issue by actboy168** [yue/yue#15]

**Comment by Fordi** [comment]
If I'm reading correctly, you'd like to have the `Label` view support `setstyle { textAlign=ALIGNMENT }`, where ALIGNMENT is one of 'left', 'right', 'center', or 'justify' (i.e., the CSS `text-align` property)?

**Comment by Fordi** [comment]
It looks like it's part of the Painter api.

I don't think cross-platform labels are consistent enough to trivially implement alignment, but you _could_ implement a simple Container view in a factory function that will draw text the way you want.

**Comment by zcbenz** [comment]
Fixed with 49e43db76b7aab2323a243ffc487f6e6f2230693.
