### ISSUE TITLE
Error: Cannot find module '...yue-trial/out/yuetrial/asar'

### ISSUE THREAD

**Issue by arunkd13** [yue/yue#164]
I am testing out yackage using a trial app but I am getting an error saying cannot find module asar. What could be going on here?:
```
~/workspace/yue-trial$ out/yuetrial 

(process:34471): Gtk-WARNING **: 09:10:48.620: Locale not supported by C library.
        Using the fallback 'C' locale.
node:internal/modules/cjs/loader:1050
  throw err;
  ^

Error: Cannot find module '/home/arun/workspace/yue-trial/out/yuetrial/asar'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:27:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.14.0
```

You can find the code here: https://github.com/arunkd13/yue-trial

I use the following command to build:
$ yackage dist out --unpack "+(*.node|*.png)"

Yue Version: 0.13.13
Operating System: Debian GNU/Linux 11 (bullseye)

**Comment by zcbenz** [comment]
The code repo https://github.com/arunkd13/yue-trial is not available.

**Comment by zcbenz** [comment]
The `main` field must be present in the `package.json`, sorry I forgot to mention it in the docs.


```js
{
  ...
  "main": "app.js",
  ...
}
```
