### ISSUE TITLE
Questions about drawing

### ISSUE THREAD

**Issue by xland** [yue/yue#166]
Yue Version: 0.13.13
Operating System: windows 10

I am implementing a drawing program with Yue.
I found that Yue only supports `Normal` and `Copy` BlendMode on Windows.
 (https://libyue.com/docs/latest/cpp/api/painter.html#setblendmode-mode)
So how do I achieve the eraser effect of a drawing?

Thanks very much.
Yue is a great GUI framework.

**Comment by zcbenz** [comment]
The backend of Painter uses GDI+ on Windows, which only has very limited bend modes, so currently it is not possible.
