### ISSUE TITLE
create textedit in scroll container  not work

### ISSUE THREAD

**Issue by wenfer** [yue/yue#167]
```
local gui = require('yue.gui')


function createcontainer(name)
    local single = gui.Container.create()
    single:setstyle { flexdirection = 'column' }
    local label = gui.Label.create(name)
    label:setstyle { padding = 10, left = 10 }
    label:setalign('start')
    single:addchildview(label)

    return single
end

function createinput(name, type)
    local single = createcontainer(name)
    local input = gui.Entry.createtype(type)
    input:setstyle { marginleft = 10, marginright = 10 }
    single:addchildview(input)
    return single
end

function createtextedit(name)
    local single = createcontainer(name)
    local edit = gui.TextEdit.create()
    edit:setstyle { marginleft = 10, marginright = 10, height = 100, width = 100, flex = 1 }
    edit:settext('1wewqewqewqeewqezcbfdgbgf')

    single:addchildview(edit)
    return single
end

local group = gui.Group.create("")

local listview = gui.Scroll.create()
local contentview = gui.Container.create()
contentview:setstyle { flexdirection = 'column' }

local singleinput = createinput("input", "normal")
local singleinput2 = createinput("password", "password")

contentview:addchildview(singleinput)
contentview:addchildview(singleinput2)

listview:setcontentsize({ width = 200, height = 500 })
listview:setcontentview(contentview)


group:setcontentview(listview)

local sssss = createtextedit("textarea")

contentview:addchildview(sssss)

local win = gui.Window.create {}

win.onclose = function() gui.MessageLoop.quit() end
win:setalwaysontop(true)
win:setcontentview(group)
win:setcontentsize({ width = 500, height = 500 })
win:center()


win:activate()
gui.MessageLoop.run()

```

the TextEdit  does not show and  console print 

`
(lua:206094): Gtk-CRITICAL **: 15:59:27.874: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:27.877: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:27.924: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:27.942: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:27.958: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:27.974: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:27.991: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.008: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.024: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.040: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.057: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.074: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.091: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.107: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.124: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.140: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.157: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.174: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(lua:206094): Gtk-CRITICAL **: 15:59:28.191: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
`

**Comment by zcbenz** [comment]
The wrapper container of TextEdit should also have its height specified:

```lua
 23 function createtextedit(name)
...
 25     single:setstyle{flex=1}
...
 32 end
```
