### ISSUE TITLE
how to create a modal window?

### ISSUE THREAD

**Issue by ChrisCatCP** [yue/yue#170]
Yue Version: Windows
Operating System: 0.13.13
how to create a modal window like MessageBox?

**Comment by Frityet** [comment]
It's the Dialog classes iirc

**Comment by ChrisCatCP** [comment]
> It's the Dialog classes iirc

i cant find it

**Comment by Frityet** [comment]
> > It's the Dialog classes iirc
> 
> i cant find it

https://libyue.com/docs/latest/cpp/api/messagebox.html

**Comment by ChrisCatCP** [comment]
> > > It's the Dialog classes iirc
> > 
> > 
> > i cant find it
> 
> https://libyue.com/docs/latest/cpp/api/messagebox.html
thanks ,but this is not what I need
modal window , not msgbox
