### ISSUE TITLE
Problem with gui.Cursor.createwithtype(...) 

### ISSUE THREAD

**Issue by deoxyimran** [yue/yue#178]
Yue Version: 0.14.1
Operating System: Linux x64-bit 

The function mentioned in the title should return a Cursor not a Font. Is this a bug or am I interpreting things wrong here?

**Comment by zcbenz** [comment]
This is a type in the docs, thanks for reporting.

Closed with https://github.com/yue/yue/commit/0e1073d7b68adae81d65377db8d2f868ef4bee9e.
