### ISSUE TITLE
Compile with /MD？

### ISSUE THREAD

**Issue by actboy168** [yue/yue#18]
The current compile option is MT, and statically linked Lua. When using lua.exe to load yue.dll, it crashes. For example, a memory created by lua.exe is freed within yue.dll.

**Comment by zcbenz** [comment]
It should not happen that memory created in lua.exe gets freed in yue.dll, as far as I know lua APIs do not manage memory from callers, can you give an example of this?

**Comment by actboy168** [comment]
Maybe I was mistaken, my lua has too much customization. I first try to locate error.

**Comment by zcbenz** [comment]
Can you share the link to the lua runtime you are using?

I tried with binaries from LuaBinary and could not reproduce the problem.
https://sourceforge.net/projects/luabinaries/files/5.3.4/Tools%20Executables/

**Comment by actboy168** [comment]
This is the lua I am using.
https://github.com/actboy168/YDWE/tree/release-1.32/OpenSource/Lua

And, here is where it can't be used with official lua.
https://github.com/actboy168/YDWE/blob/release-1.32/OpenSource/Lua/lobject.h#L79

**Comment by zcbenz** [comment]
The v0.6.0 binaries should be working with third party runtime now, please let me know if it still does not run.

Closed with https://github.com/yue/yue/commit/dfccc85f0cff2977624fa2d4a776e699fc814913.
