### ISSUE TITLE
MessageBox onResponse not getting triggered 

### ISSUE THREAD

**Issue by asrient** [yue/yue#181]
Yue Version: 0.15.3
Operating System: Windows 11

Could not get [onResponse](https://libyue.com/docs/latest/js/api/messagebox.html#onresponse-self-response) to work.

```js
import gui from 'gui';

global.win = gui.Window.create({});

const msg = gui.MessageBox.create();
msg.setTitle('Test Message Box');
msg.setText('How would you like to exit?');

msg.addButton('Exit Normally', 0);
msg.setCancelResponse(0);
msg.addButton('Exit With Error', 1);

msg.onResponse = (self, response) => process.exit(response);

msg.showForWindow(global.win);

global.msg = msg;
```

Expected Result: process exit with proper exit code.
Current Result: process does not exit.

Also tried using `msg.onResponse.connect(cb)` but this would result in error:
```
TypeError: Cannot read properties of undefined (reading 'connect')
```

Also `onResponse` is marked as `any` in type definitions.

**Comment by zcbenz** [comment]
Thanks for reporting this, this has been fixed by https://github.com/yue/yue/commit/7ec10676a81a407bc01f6074342d5e7a4b34c37a.

> Also `onResponse` is marked as `any` in type definitions.

It was a lazy placeholder then totally forgotten, it should be defined as getter/setter.
