### ISSUE TITLE
Async callbacks are not working as expected

### ISSUE THREAD

**Issue by devallabharath** [yue/yue#182]
Yue Version: v0.15.4
Operating System: Mac Sequoia 15.1

```js
import gui from 'gui'
import axios from 'axios'

const view = gui.Container.create()
const btn = gui.Button.create('Get')
view.addChildView(btn)

btn.onClick = async () => {
  console.log('clicked') // working
  const { data } = await axios('https://google.com')
  console.log('finished') // not working
  console.log(data) // not working
}

export default view
```
The await axios in button callback is not executing. Please anyone help me on this.

**Comment by zcbenz** [comment]
Are you running with the official Node.js binary or [Yode](https://github.com/yue/yode)?

**Comment by devallabharath** [comment]
Official node 18

**Comment by zcbenz** [comment]
Thanks for reporting back. Unfortunately the design of Node's message loop makes it impossible to run GUI message loop perfectly with the official binary, you have to live with Yode.
