### ISSUE TITLE
Where can i find yue.so or yue.lib? Is it required for use or is it optional? Why you didn't include yue.so/yue.lib in release archive?

### ISSUE THREAD

**Issue by JohnClaw** [yue/yue#183]
Yue Version: latest
Operating System: Windows 11

**Comment by zcbenz** [comment]
There is no prebuilt libraries for C++, I tried that before but it was very hard to get everything right on user's side.

It is recommended to build from source code, you can download https://github.com/yue/yue/releases/download/v0.15.4/libyue_v0.15.4_win.zip and there is a CMake file can be used to build a sample app directly.

There is also a manual guide in https://libyue.com/docs/latest/cpp/guides/getting_started.html and a boilerplate app https://github.com/yue/boilerplate-cpp.
