### ISSUE TITLE
Menu initially not sensitive in node editor example on macOS

### ISSUE THREAD

**Issue by Fordi** [yue/yue#19]
Example from: https://github.com/yue/yue-sample-apps/tree/master/editor

## Environment

* OS: macOS 10.13.3
* node: 8.1.4
* node-gui: 0.3.1
* download-yue: 1.1.1

## Description:

Starting the example with `node .`, the editor mostly works, but the menu at the top of the screen is not sensitive until the editor window has been de-focused and re-focused.  There doesn't appear to be anything in the example code causing this.

**Comment by zcbenz** [comment]
This is unfortunately a limitation of macOS when you create windows from command line programs. If you package your app into a macOS app bundle, the menu would work fine.
