### ISSUE TITLE
drawCanvas / drawCanvasFromRect missing in node-gui

### ISSUE THREAD

**Issue by Fordi** [yue/yue#20]
## Environment

* OS: macOS 10.13.3
* node: 8.1.4
* node-gui: 0.3.1
* download-yue: 1.1.1

## Code sample

    const gui = require('gui');
    const win = gui.Window.create({});
    const OBJ_CONST = (obj) => Object.seal(Object.freeze(obj));
    const SIZE = OBJ_CONST({ width: 400, height: 400 });
    win.onClose = () => gui.MessageLoop.quit();
    win.setContentSize(SIZE);
    const contentView = gui.Container.create();
    const canvas = gui.Canvas.create(SIZE, 1.0);
    contentView.onDraw = (self, painter, dirty) => {
        let tgtRect = Object.assign({ x: 0, y: 0 }, SIZE);
        if (painter) {
            console.log(painter, painter.drawCanvas);
            try {
              painter.drawCanvas(canvas, tgtRect);
            } catch (e) {
              console.error(e);
            }
        }
    };
    win.setContentView(contentView);
    win.center();
    win.activate();
    gui.MessageLoop.run();
    process.exit(0);

## Expectation

`painter.drawCanvas` should be present, according to the docs, and should copy the contents of the passed Canvas (`canvas`) to the Container, scaled to fit the passed RectF (`tgtRect`).

Should output on the console: `yue.Painter {} [Function: drawCanvas]`

## Actual

Application reports:

    yue.Painter {} undefined
    TypeError: painter.drawCanvas is not a function
        at Function.contentView.onDraw (/Users/bellio851/test/yue/index.js:13:19)
        at Object.<anonymous> (/Users/bellio851/test/yue/index.js:22:5)
        ...

### Side note:

The reason the `if (painter)` is there is that sometimes the first call of `onDraw` passes null for the `painter` argument.  I get similar results using `drawCanvasFromRect`.

The code sample is simplified from the Lua sample found here: 

https://github.com/yue/yue-sample-apps/blob/master/drawing/lua/drawing.lua

**Comment by zcbenz** [comment]
Closed with #22.
