### ISSUE TITLE
[node-gui] Get an Image from ArrayBuffer

### ISSUE THREAD

**Issue by neowinx** [yue/yue#23]
Hello,

First, I want to express my gratitude for making this library, I find it very cool... and having that _coolness_ without bloating my app it is a nice plus. Nice work! :+1: 

I am using [opencv4nodejs](https://www.npmjs.com/package/opencv4nodejs) in my application that captures some video footage and run some calculations in order to find some objects.

My goal is to display an [Image](http://libyue.com/docs/v0.3.1/js/api/image.html) somewhere in a [Container](http://libyue.com/docs/v0.3.1/js/api/container.html) or [Canvas](http://libyue.com/docs/v0.3.1/js/api/canvas.html) and **refresh** it with the calculation results, let's say, **every 15 frames**.

So, I searched a little and cannot find an optimal way to draw the image from memory (a javascript [ArrayBuffer](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/ArrayBuffer)) since the [Image](http://libyue.com/docs/v0.3.1/js/api/image.html) class only have the [createFromPath(path)](http://libyue.com/docs/v0.3.1/js/api/image.html#createfrompath-path) constructor. And writting the results on an file to disk in order to show it every time is refreshed is rather unnaceptable.

So, I want to ask if there is a way to create an [Image](http://libyue.com/docs/v0.3.1/js/api/image.html) class from the [ArrayBuffer](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/ArrayBuffer), or if someone already has done it, if he or she can point me in the right direction since I am a little lost here.

Thanks very much in advance and best regards

**Comment by zcbenz** [comment]
Currently we don't have an API in yue to create images from memory, looks a good thing to have.

**Comment by neowinx** [comment]
Well, I found that **Gdi** has [this](https://msdn.microsoft.com/en-us/library/windows/desktop/ms535410(v=vs.85).aspx) constructor for the [Image](https://msdn.microsoft.com/en-us/library/windows/desktop/ms534462(v=vs.85).aspx) class that receives an [IStream](https://msdn.microsoft.com/en-us/library/windows/desktop/ms535410(v=vs.85).aspx)

Not so sure how the conversion [ArrayBuffer](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/ArrayBuffer) :arrow_right: [IStream](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380034(v=vs.85).aspx) would be here

Also for **Gtk**, there is [gdk_pixbuf_new_from_stream](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-File-Loading.html#gdk-pixbuf-new-from-stream) and even a [gdk_pixbuf_new_from_stream_async](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-File-Loading.html#gdk-pixbuf-new-from-stream-async) that could serve us for the same porpuse (I guess)

Again, not sure how to [ArrayBuffer](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/ArrayBuffer) :arrow_right: [GInputStream](https://developer.gnome.org/gio/unstable/GInputStream.html#GInputStream-struct) but I guess is doable since I found some node libraries that do that (links down below)

As for  **Cocoa**, I guess initializing an [NSImage](https://developer.apple.com/documentation/appkit/nsimage) with something like [init?(data: Data)](https://developer.apple.com/documentation/appkit/nsimage/1519941-init) should do the trick, but I cannot test it since **I don't use mac** in my daily basis

_Some node libs that convert from streams to ArrayBuffer examples (I think)_
- opencv:
[io.cc decode from ArrayBuffer](https://github.com/justadudewhohacks/opencv4nodejs/blob/d59caf998cf0e90203ed2aaa7046248e9e4ddccb/cc/modules/io/io.cc#L153)

- robotjs:
[screengrab - X11](https://github.com/octalmage/robotjs/blob/master/src/screengrab.c#L72)
[screengrab - Windows](https://github.com/octalmage/robotjs/blob/master/src/screengrab.c#L130)

I don't know if I have the knowledge and time to implement this so I just post here what I found in order to put my grain of sand into this matter.

Hope it helps to get into this goal

Have a good day everyone! :smiley:

**Comment by zcbenz** [comment]
Thanks for finding out all the references, closed with fad6136a1417401d5536f2238e52a678750cb3c4, c6dad1cba91f5651d2af0167dcabd1a53fedf9b0, bce6a42904970027b2a8a3cfbe4db95127260710.
