### ISSUE TITLE
add new API to Canvas class to clear its content?

### ISSUE THREAD

**Issue by sunbingfengPI** [yue/yue#24]
I want to use canvas to do offline render, and new content can be drawn to canvas successfully, but the old content cannot be cleaned.

So I guess if it might be ok to add a new API to Canvas class to clear its content totally?

thanks

**Comment by zcbenz** [comment]
👍

**Comment by arjndr** [comment]
+1 on this, but for the moment a "workaround" I've been using : `schedulePaint()` and `onDraw()` on Views

**Comment by zcbenz** [comment]
Closed with https://github.com/yue/yue/commit/d2daea22c6aa12ba5eea4af384e5573156b15039.
