### ISSUE TITLE
feature:treeview listview

### ISSUE THREAD

**Issue by sunwangme** [yue/yue#25]
how about them?

**Comment by zcbenz** [comment]
It is really hard to implement a fully-featured tree view that uses native controls on all platforms, I'll probably implement it some day in future.

For now you can only simulate listview/treeview with `Container` class, like how people does with div/CSS in web.

**Comment by zcbenz** [comment]
`Table` has been added in v0.6.0 which can be used as list view.

**Comment by sunwangme** [comment]
加油！春节快乐，万事如意！
