### ISSUE TITLE
Compatibility with unofficial lua.

### ISSUE THREAD

**Issue by actboy168** [yue/yue#26]
I have a modify lua implementation. Compared to the official lua, it has the same api and the same behavior. But the memory layout of `lua_State` is different.

So inline `lstate.h` will make it crash.
https://github.com/yue/yue/blob/master/lua/inline.h

Can you add an option to turn off this inline? Thanks.

**Comment by zcbenz** [comment]
After some testing it seems inlining the functions does not have much affect on performance, I'm going to remove it.

**Comment by zcbenz** [comment]
Closed with a815a23.
