### ISSUE TITLE
any plan for mobile (iOS/Android)?

### ISSUE THREAD

**Issue by wanjochan** [yue/yue#32]
as title.

thanks and cheers

**Comment by zcbenz** [comment]
I do plan to add mobile support in future when this project is close to feature complete and has gotten enough users. But apparently by "future" it could mean > 3 years.

**Comment by justdie386** [comment]
So, any news about mobile support?

**Comment by nawbc** [comment]
So, any news about mobile support?

**Comment by justdie386** [comment]
Mhm, would really like to be able to make a lua gui app for ios, since there's much only game engines for that, which is less than ideal
