### ISSUE TITLE
Advertised C++ example does not link

### ISSUE THREAD

**Issue by gvanem** [yue/yue#34]
I've been struggling for 2 hours trying to build `libyue.lib` before giving up. The [documentation](http://libyue.com/docs/v0.4.0/cpp/guides/getting_started.html) states:
> Enter the directory of libyue and create a build sub-directory for building.

What `libyue` directory is that?

So I downloaded the pre-built 0.4.0 .zip and even the `libyue.lib` seems to be missing this symbol:
```
main.obj : error LNK2019: unresolved external symbol 
"private: bool __thiscall base::subtle::RefCountedBase::CalledOnValidSequence(void)
const " (?CalledOnValidSequence@RefCountedBase@subtle@base@@ABE_NXZ) referenced in function _WinMain@16
```
when compiling and linking this [sample](http://libyue.com/docs/v0.4.0/cpp/guides/getting_started.html).

*PS*. I used a simple GNU-makefile to build for MSVC-2017 (32-bit).

*Edit*. Building in `_DEBUG`-mode (`-MTd`) is okay.

**Comment by zcbenz** [comment]
Before I fix the documentation, you might want to fork https://github.com/yue/muban, which is template C++ project.

**Comment by zcbenz** [comment]
We now have tests automatically validating the C++ library, steps can be found at:
https://github.com/yue/yue/blob/master/scripts/test_libyue.js#L40-L78

For Windows currently we only test Visual Studio build.
