### ISSUE TITLE
[Lua] TextEdit.shouldinsertnewline doesn't work

### ISSUE THREAD

**Issue by khanhas** [yue/yue#36]
Code:
```lua
local pickFolderForm = gui.TextEdit.create()
pickFolderForm:setstyle{width= 400, height: 25}
pickFolderForm:settext("Type in folder")

function pickFolderForm.shouldinsertnewline( self )
    print(self)
    return false
end
```
Video: https://streamable.com/jpn4p

**Comment by zcbenz** [comment]
I'm trying to reproduce with following code on Windows 8.1 but it seems to work fine:

```lua
local gui = require('yue.gui')

local win = gui.Window.create{}
win.onclose = function() gui.MessageLoop.quit() end

local entry = gui.TextEdit.create()
entry:setstyle{flex=1}

function entry.shouldinsertnewline(self)
  print(self)
  return false
end

local view = gui.Container.create()
view:addchildview(entry)
win:setcontentview(view)
win:setcontentsize{width=400, height=400}

win:center()
win:activate()
entry:focus()

gui.MessageLoop.run()
```

Can you tell me following information?

* Your operating system version.
* The version of Yue.
* Are you using the independent version (`yue.exe`) or the module version (`yue.dll`)?

**Comment by khanhas** [comment]
- Windows 10 version 1803 (build 17134)
- Yue 0.4.3
- yue.dll 
and I don't think there is standalone `yue.exe`
I just reinstalled my Windows recently and the problem seem a little better than before: input box doesn't disappear now and scrollbar is available on the right. 
![image](https://user-images.githubusercontent.com/26436809/40264553-a61de7d2-5b50-11e8-9e91-ce94d5773119.png)

But 
```lua
function pickFolderForm.shouldinsertnewline(self)
  print(self)
  return false
end
```
still doesn't prevent me from inserting new line when I hit enter.

**Comment by zcbenz** [comment]
Can you try using https://github.com/yue/yue/releases/download/v0.4.3/yue_v0.4.3_win_x86.zip to run the app and see if the result is the same?

**Comment by khanhas** [comment]
Oh hey it works correctly!

**Comment by khanhas** [comment]
Should I close this issue or just leave it to remind you to fix?

**Comment by zcbenz** [comment]
On Windows the executable has to be compiled as GUI programs (aka Windows Subsystem) to claim it supports GUI, otherwise Windows would fallback to use compatible mode when the executable creates GUI.

However most `lua.exe` distributions are compiled as Console programs, which would have lots of quirks when showing GUI inside them. The solution is to recompile `lua.exe` as GUI program, or to use the `yue.exe` distribution provided here, it is not something we can solve at module level.
