### ISSUE TITLE
sample_app cmake build fails in Ubuntu 16.04 x86_64 with linux_x64 release 2.0

### ISSUE THREAD

**Issue by ahungry** [yue/yue#4]
Attempting to build it from this release:

https://github.com/yue/yue/releases/download/v0.2.0/libyue_v0.2.0_linux_x64.zip

```
[ 50%] Linking CXX executable sample_app
../lib/libyue.a(lifetime_gtk.o): In function `nu::Lifetime::PlatformInit()':
/home/travis/build/yue/yue/out/Release/../../nativeui/gtk/lifetime_gtk.cc:23: undefined reference to `gtk_init'
```
(followed by about 500 other errors of undefined symbol references)

This worked fine on Arch Linux - judging from pkg-config output, I don't think I'm missing any libs.

**Comment by ahungry** [comment]
My cmake knowledge is limited, but this seemed to fix it:

```cmake
# Linux configuration                                                                                                                                                                                                                          
if(UNIX AND NOT APPLE)
  find_package(PkgConfig)
  pkg_search_module(GTK3 REQUIRED gtk+-3.0)
  pkg_search_module(X11 REQUIRED x11)
  #target_link_libraries(${APP_NAME}                                                                                                                                                                                                           
  #                      pthread dl ${GTK3_LIBRARIES} ${X11_LIBRARIES})                                                                                                                                                                        
  target_include_directories(${APP_NAME} PUBLIC
                             ${GTK3_INCLUDE_DIRS} ${X11_INCLUDE_DIRS})
  target_compile_options(${APP_NAME} PUBLIC
                         ${GTK3_CFLAGS_OTHER} ${X11_CFLAGS_OTHER})
  target_link_libraries(${APP_NAME}
			optimized ${CMAKE_SOURCE_DIR}/lib/libyue.a
			debug ${CMAKE_SOURCE_DIR}/lib/libyued.a
			pthread dl ${GTK3_LIBRARIES} ${X11_LIBRARIES})
  target_compile_definitions(${APP_NAME} PUBLIC _GLIBCXX_USE_CXX11_ABI=0)
  set_target_properties(${APP_NAME} PROPERTIES LINK_FLAGS
                        "-fdata-sections -ffunction-sections -Wl,--gc-section")
endif()
```
(note - the change is including pthread dl ${GTK3_LIBRARIES} ${X11_LIBRARIES} at the end of the target_link_libraries block, after optimize and debug lines)

I'll see if this alteration works on Arch Linux without breaking it there tonight.

**Comment by zcbenz** [comment]
Probably related to cmake version?

**Comment by topillar** [comment]
Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

[ 50%] Linking CXX executable sample_app.exe
   Creating library sample_app.lib and object sample_app.exp
main.cc.obj : error LNK2019: unresolved external symbol "private: bool __cdecl b
ase::subtle::RefCountedBase::CalledOnValidSequence(void)const " (?CalledOnValidS
equence@RefCountedBase@subtle@base@@AEBA_NXZ) referenced in function "protected:
 void __cdecl base::subtle::RefCountedBase::AddRef(void)const " (?AddRef@RefCoun
tedBase@subtle@base@@IEBAXXZ)
dwmapi.lib(dwmapi.dll) : error LNK2001: unresolved external symbol __delayLoadHe
lper2
dwmapi.lib(dwmapi.dll) : error LNK2001: unresolved external symbol __delayLoadHe
lper2
setupapi.lib(SETUPAPI.dll) : error LNK2001: unresolved external symbol __delayLo
adHelper2
setupapi.lib(SETUPAPI.dll) : error LNK2001: unresolved external symbol __delayLo
adHelper2
setupapi.lib(SETUPAPI.dll) : error LNK2001: unresolved external symbol __delayLo
adHelper2
powrprof.lib(POWRPROF.dll) : error LNK2001: unresolved external symbol __delayLo
adHelper2
sample_app.exe : fatal error LNK1120: 2 unresolved externals
LINK failed. with 1120
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return cod
e '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.

**Comment by zcbenz** [comment]
I confirm this is related to cmake version, fixed with https://github.com/yue/yue/commit/dbb8b33f31d34985996477a77e88ffd15f7626e2.
