### ISSUE TITLE
error when creating the tray

### ISSUE THREAD

**Issue by pkisztelinski** [yue/yue#45]
hello. I'm trying to create app with tray icon and I'm getting an error. 

`Error when running script: tray.lua:6: attempt to call a nil value (field 'create')`

code: 

```
local gui = require('yue.gui')

local win = gui.Window.create{}

local tray_icon = gui.Image.createfrompath('icon.png')
local tray = gui.Tray.create(tray_icon)

win.onclose = function() gui.MessageLoop.quit() end
win:setcontentsize{width=500, height=500}

win:center()
win:activate()
gui.MessageLoop.run()
```

os: win 8.1
yue version: lua_yue_lua_5.3_v0.4.3_win_x64

**Comment by zcbenz** [comment]
It is an error in documents, the create functions should be `Tray.createwithtitle` and  `Tray.createwithimage`
