### ISSUE TITLE
How to make a text wrapped?

### ISSUE THREAD

**Issue by oyyd** [yue/yue#47]
I can use `label` to display a text but the text will be truncated when it's longer than the width of its container:

<img width="456" alt="20180525132955" src="https://user-images.githubusercontent.com/5847587/40527589-ca286016-601f-11e8-9736-15cc32a11e6a.png">

I want to make it wrapped rather than truncated. I have tried the `flexWrap: 'wrap'` layout property but it doesn't work as expected.

Maybe I have missed some components or layout properties?

**Comment by zcbenz** [comment]
Currently we don't have support for wrapping, looks like a critical feature to have.
