### ISSUE TITLE
What does yue use on Linux & MacOS do draw the ui?

### ISSUE THREAD

**Issue by Darkle** [yue/yue#49]
Hi, in the docs it mentions that yue uses GDI+ to draw the ui on windows, but I didn't see any info about what yue uses to draw the ui on Linux and MacOS.

Cheers.

**Comment by dariocravero** [comment]
Mac seems to be using Cocoa https://github.com/yue/yue/tree/master/nativeui/mac and I'd assume Linux uses Gtk https://github.com/yue/yue/tree/master/nativeui/gtk

**Comment by zcbenz** [comment]
Yeah @dariocravero's answer is precise.
