### ISSUE TITLE
In C++ bindings, nu::TextEdit without a SetStyle("flex", "1") call will never render

### ISSUE THREAD

**Issue by ahungry** [yue/yue#5]
This is not documented / mentioned in the doc for TextEdit or the base View.

Other components such as Button/Label seem to render fine without an explicit SetStyle call.

I would make a mention that it is necessary for rendering.

**Comment by zcbenz** [comment]
The layout works similar to browser, by default all elements take empty spaces. Some elements have default style that takes up minimum size, I agree I should have the behavior explicitly documented, will do it in future.
