### ISSUE TITLE
What tool is used to generate documentation?

### ISSUE THREAD

**Issue by slice** [yue/yue#54]
I am interested in the tool that is used to build [the documentation](https://libyue.com/docs/latest/lua/index.html), it looks very nice and clean.

Is this tool open source or available somewhere? I might use it for my own projects.

Thanks!

**Comment by zcbenz** [comment]
You can find the script to generate the site at `scripts/create_docs.js`, and the raw documentation is located under `docs/`. While the whole documentation stack is under public domain, it is highly specialized for this project and you will have to do some modifications to make it work for general purpose.
