### ISSUE TITLE
Toolbar Item

### ISSUE THREAD

**Issue by eveningkid** [yue/yue#55]
Hi,

I sadly can't find any way to add a toolbar item to my [toolbar](https://libyue.com/docs/latest/js/api/toolbar.html) on macOS.

There is [a definition of a toolbar item](https://libyue.com/docs/latest/js/api/toolbar_item.html) but I couldn't find how to append it to the toolbar.

Thank you for your help!

**Comment by afaur** [comment]
@eveningkid 
Could you share an example repository with the code that is currently not working? 
Having a broken example which is then made to work may help others getting started as well.
I wouldn't mind helping with this if you could provide a repository link on this issue.

**Comment by eveningkid** [comment]
@afaur, sure.

I didn't come up with a repository for that, as the following code speaks for itself.

```js
const gui = require('gui');

const win = gui.Window.create({});
win.setContentSize({ width: 400, height: 250 });

const toolbar = gui.Toolbar.create('toolbar');
win.setToolbar(toolbar);
// How to add toolbar items to the toolbar?

const contentView = gui.Container.create();
win.setContentView(contentView);

win.center();
win.activate();
```

The question is: how to add toolbar items to the toolbar?
I guess that this part, adding customized elements to that toolbar, is missing.

**Comment by afaur** [comment]
@eveningkid 

Looks like this may not be able to be done in node as of now:

```js
const gui = require('gui')

const win = gui.Window.create({})
win.setContentSize({ width: 400, height: 250 })

const toolbar = gui.Toolbar.create('test')

// Specify Toolbar Items display mode by passing an item of type Toolbar DisplayMode
//toolbar.setDisplayMode(<yue.Toolbar.DisplayMode>)

// Specify Toolbar Items by creating an array of type Toolbar Items
//const toolbarItems = [<gui.Toolbar.Item>]

// Specify Toolbar identifiers
// Implemented but cannot create an array of the type of items it requires
toolbar.setDefaultItemIdentifiers()
// Passing [{label: 'test'}] would give you an error since the object is not of correct type
// TypeError: Error processing argument at index 0, conversion failure from Array to Array

win.setToolbar(toolbar)

const contentView = gui.Container.create()
win.setContentView(contentView)

win.center()
win.activate()
```

Findings/References:

- Toolbar Item Type
  [[node binding code] Type is defined here but cannot create an object of this type]
 https://github.com/yue/yue/blob/a9299f33905b7433d200bc88544ca4697ed9f4f8/node_yue/binding_gui.cc#L986-L1006

- Toolbar instance: setDefaultItemIdentifiers 
  [[docs code] implemented but cannot pass array of correct type from node] [type conversion failure]
https://github.com/yue/yue/blob/1c64f5b3e7c4908d264d327e52b3f4a8ff8e5549/docs/api/toolbar.yaml#L39-L44

- Window instance: setToolbar
  [works correctly but cannot make a toolbar with items before passing]
    https://github.com/yue/yue/blob/master/node_yue/binding_gui.cc#L1130-L1137
    https://github.com/yue/yue/blob/master/nativeui/mac/window_mac.mm#L339-L342

Additional Notes:

  - I don't think there is a way to specify Toolbar DisplayMode as well.

**Comment by eveningkid** [comment]
Thanks a lot for looking into it. This is what I thought when I checked these files back then...
So does it actually work using Lua?

By the way, using node, `setDisplayMode(mode)` does work given a `string` among [the ones there](https://libyue.com/docs/latest/js/api/toolbar_displaymode.html).

I hope this could be implemented for node though...

**Comment by afaur** [comment]
By the way, using node, setDisplayMode(mode) does work given a string among the ones there.
  - Thanks for letting me know that this is working.

"So does it actually work using Lua?"
  - I am unsure if it would work in Lua right now. 
  - I may be wrong about it not working in node, but it seems like either: 
    - The binding layer needs the ability to create the `Toolbar::Item` type
    - The method to add items should coerce an array of js objects to the specialized `Toolbar::Item` types.

If you want to get a really basic toolbar set up I put together an example on how you could make one with views and layout styling.

This would not have the shared toolbar (based on create(name)) capabilities that gui.Toolbar offers but I think that could be done by adding the toolbar logic in a function.

It uses a button but removes the button border styling to make it look like a label and binds an onClick. The onClick function will add a label to the middle of the view.

```js
const gui = require('gui')

const win = gui.Window.create({ frame: true, transparent: false })

win.setAlwaysOnTop(true)
win.setContentSize({ width: 400, height: 400 })

const view = gui.Container.create()

view.setStyle({
  'flex-direction': 'column',
  'justify-content': 'space-between',
  'padding-bottom': 200,
})

view.setMouseDownCanMoveWindow(true)

const toolbar = gui.Container.create()

toolbar.setStyle({'flex-direction': 'row', 'padding-left': 15})

view.addChildView(toolbar)

const fileButton = gui.Button.create('file')

fileButton.setEnabled(true)
fileButton.setHasBorder(false)

fileButton.onClick = _ => view.addChildView(gui.Label.create('File Clicked'))

toolbar.addChildView(fileButton)

view.onDraw = (self, painter) => {
  painter.setStrokeColor('#BCBCBC')
  painter.setLineWidth(1)
  painter.beginPath()
  painter.moveTo({x: 0, y: 30})
  painter.lineTo({x: 400, y: 30})
  painter.stroke()
}

win.setContentView(view)
win.setVisible(true)
win.center()
win.activate()

!process.versions.yode && (gui.MessageLoop.run() && process.exit(0))
```
<img width="402" alt="emulate-toolbar" src="https://user-images.githubusercontent.com/898523/42211473-8bf19b3e-7e68-11e8-865e-4924d8eb2dea.png">

**Comment by eveningkid** [comment]
@afaur hehe, good workaround...but obviously I hope this could be done natively instead. Thanks a lot for investing so much of your time into this, it's really nice of you! :)

@zcbenz I wish that we could get an update on this. Is it planned to be added in a near future?

**Comment by zcbenz** [comment]
Sorry for the late reply, I have added documentation on how to use Toolbar:
https://libyue.com/docs/v0.6.0/js/api/toolbar.html
