### ISSUE TITLE
Generate typescript definitions

### ISSUE THREAD

**Issue by zaaack** [yue/yue#60]

**Comment by mrkmg** [comment]
I would love to have typescript defs.

**Comment by mrkmg** [comment]
I have taken up to writing out all the Typescript Defs. I will make a PR once completed.

**Comment by mrkmg** [comment]
https://github.com/yue/node-gui/pull/24

**Comment by mrkmg** [comment]
I believe the types are complete, or nearly complete.

**Comment by cancerberoSgx** [comment]
@mrkmg  I'm just trying the library for the first time and your typings are great Probably will add a couple of details from examples, but getting started with typings is awesome. Authors should npm publish them  though  - I realized by chance there were there in the sources... fortunately. thanks

**Comment by zcbenz** [comment]
Closed with https://github.com/yue/yue/commit/1ab61c725d986dc5d2fba8f55a0b91bc128a024c.
