### ISSUE TITLE
How to get the tray position for a tray app?

### ISSUE THREAD

**Issue by zaaack** [yue/yue#61]
Hi, thanks for your awesome project! I'm planning to write a tray app, something like  https://github.com/maxogden/menubar via yue, but I can't find how to get the position of tray on the screen and screen size in the documents.

**Comment by Skayo** [comment]
Need it too

**Comment by zcbenz** [comment]
Closed with https://github.com/yue/yue/commit/cb9419b1e1948ff604e46a00d1aa5a3ca012e933.
