### ISSUE TITLE
cannot install use npm

### ISSUE THREAD

**Issue by KsRyY** [yue/yue#62]
log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator.WIN-DKN9OK77VLJ\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'gui' ]
2 info using npm@6.2.0
3 info using node@v10.7.0
4 verbose npm-session 1485adf0ac06def0
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/gui 1894ms (from cache)
8 silly pacote tag manifest for gui@latest fetched in 2134ms
9 timing stage:loadCurrentTree Completed in 5152ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule gui@0.5.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/download-yue 967ms (from cache)
18 silly pacote range manifest for download-yue@2.x fetched in 1002ms
19 silly resolveWithNewModule download-yue@2.0.0 checking installable status
20 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 1064ms
21 timing stage:loadIdealTree Completed in 1078ms
22 silly currentTree SodaScriptIDE
23 silly idealTree SodaScriptIDE
23 silly idealTree +-- download-yue@2.0.0
23 silly idealTree `-- gui@0.5.0
24 silly install generateActionsToTake
25 timing stage:generateActionsToTake Completed in 18ms
26 silly diffTrees action count 2
27 silly diffTrees add download-yue@2.0.0
28 silly diffTrees add gui@0.5.0
29 silly decomposeActions action count 16
30 silly decomposeActions fetch download-yue@2.0.0
31 silly decomposeActions extract download-yue@2.0.0
32 silly decomposeActions preinstall download-yue@2.0.0
33 silly decomposeActions build download-yue@2.0.0
34 silly decomposeActions install download-yue@2.0.0
35 silly decomposeActions postinstall download-yue@2.0.0
36 silly decomposeActions finalize download-yue@2.0.0
37 silly decomposeActions refresh-package-json download-yue@2.0.0
38 silly decomposeActions fetch gui@0.5.0
39 silly decomposeActions extract gui@0.5.0
40 silly decomposeActions preinstall gui@0.5.0
41 silly decomposeActions build gui@0.5.0
42 silly decomposeActions install gui@0.5.0
43 silly decomposeActions postinstall gui@0.5.0
44 silly decomposeActions finalize gui@0.5.0
45 silly decomposeActions refresh-package-json gui@0.5.0
46 silly install executeActions
47 silly doSerial global-install 16
48 verbose correctMkdir C:\Users\Administrator.WIN-DKN9OK77VLJ\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
49 timing audit compress Completed in 11ms
50 info audit Submitting payload of 353bytes
51 verbose lock using C:\Users\Administrator.WIN-DKN9OK77VLJ\AppData\Roaming\npm-cache\_locks\staging-434453f6dbf14ad7.lock for J:\SodaScriptIDE\node_modules\.staging
52 silly doParallel extract 2
53 silly extract download-yue@2.0.0
54 silly extract gui@0.5.0
55 silly tarball trying download-yue@2.x by hash: sha512-AczZ5yj1+SsW7pj9vlupDFB0KL6GgRPBXs1mOWCVb8V142CrDzeYOTGPOujIxysHQF7e5g3x0geaVF5rej2oKw==
56 silly tarball trying gui@latest by hash: sha512-O1iTA5VwotFIAbS3T5kfz+UASWpm+YlxP/gr6TQRK/DFiQ2ja8iAxZ2zaQZKc3zJicYs5EiupRRx+9ku2kmtzw==
57 silly extract gui@latest extracted to J:\SodaScriptIDE\node_modules\.staging\gui-9060ddab (187ms)
58 silly extract download-yue@2.x extracted to J:\SodaScriptIDE\node_modules\.staging\download-yue-ed42c3ac (240ms)
59 timing action:extract Completed in 252ms
60 silly doReverseSerial unbuild 16
61 silly doSerial remove 16
62 silly doSerial move 16
63 silly doSerial finalize 16
64 silly finalize J:\SodaScriptIDE\node_modules\download-yue
65 silly finalize J:\SodaScriptIDE\node_modules\gui
66 timing action:finalize Completed in 43ms
67 silly doParallel refresh-package-json 2
68 silly refresh-package-json J:\SodaScriptIDE\node_modules\download-yue
69 silly refresh-package-json J:\SodaScriptIDE\node_modules\gui
70 timing action:refresh-package-json Completed in 97ms
71 silly doParallel preinstall 2
72 silly preinstall download-yue@2.0.0
73 info lifecycle download-yue@2.0.0~preinstall: download-yue@2.0.0
74 silly preinstall gui@0.5.0
75 info lifecycle gui@0.5.0~preinstall: gui@0.5.0
76 timing action:preinstall Completed in 9ms
77 silly doSerial build 16
78 silly build download-yue@2.0.0
79 info linkStuff download-yue@2.0.0
80 silly linkStuff download-yue@2.0.0 has J:\SodaScriptIDE\node_modules as its parent node_modules
81 verbose linkBins [ { 'download-yue': 'download-yue.js' },
81 verbose linkBins   'J:\\SodaScriptIDE\\node_modules\\.bin',
81 verbose linkBins   false ]
82 silly build gui@0.5.0
83 info linkStuff gui@0.5.0
84 silly linkStuff gui@0.5.0 has J:\SodaScriptIDE\node_modules as its parent node_modules
85 timing action:build Completed in 28ms
86 silly doSerial global-link 16
87 silly doParallel update-linked 0
88 silly doSerial install 16
89 silly install download-yue@2.0.0
90 info lifecycle download-yue@2.0.0~install: download-yue@2.0.0
91 silly install gui@0.5.0
92 info lifecycle gui@0.5.0~install: gui@0.5.0
93 timing action:install Completed in 3ms
94 silly doSerial postinstall 16
95 silly postinstall download-yue@2.0.0
96 info lifecycle download-yue@2.0.0~postinstall: download-yue@2.0.0
97 silly postinstall gui@0.5.0
98 info lifecycle gui@0.5.0~postinstall: gui@0.5.0
99 verbose lifecycle gui@0.5.0~postinstall: unsafe-perm in lifecycle true
100 verbose lifecycle gui@0.5.0~postinstall: PATH: C:\Users\Administrator.WIN-DKN9OK77VLJ\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;J:\SodaScriptIDE\node_modules\gui\node_modules\.bin;J:\SodaScriptIDE\node_modules\.bin;C:\Users\Administrator.WIN-DKN9OK77VLJ\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\ActiveState Komodo IDE 11\;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;K:\jdk-1.8.0_162\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Brackets\command;C:\Program Files\Git\cmd;C:\Program Files\Bandizip\;C:\Users\Administrator.WIN-DKN9OK77VLJ\AppData\Roaming\npm
101 verbose lifecycle gui@0.5.0~postinstall: CWD: J:\SodaScriptIDE\node_modules\gui
102 silly lifecycle gui@0.5.0~postinstall: Args: [ '/d /s /c', 'node install.js' ]
103 timing audit submit Completed in 1422ms
104 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1419ms
105 timing audit body Completed in 1ms
106 silly lifecycle gui@0.5.0~postinstall: Returned: code: 1  signal: null
107 info lifecycle gui@0.5.0~postinstall: Failed to exec postinstall script
108 timing action:postinstall Completed in 1950ms
109 verbose unlock done using C:\Users\Administrator.WIN-DKN9OK77VLJ\AppData\Roaming\npm-cache\_locks\staging-434453f6dbf14ad7.lock for J:\SodaScriptIDE\node_modules\.staging
110 timing stage:rollbackFailedOptional Completed in 22ms
111 timing stage:runTopLevelLifecycles Completed in 9063ms
112 silly saveTree SodaScriptIDE
112 silly saveTree `-- gui@0.5.0
112 silly saveTree   `-- download-yue@2.0.0
113 warn enoent ENOENT: no such file or directory, open 'J:\SodaScriptIDE\package.json'
114 verbose enoent This is related to npm not being able to find a file.
115 warn SodaScriptIDE No description
116 warn SodaScriptIDE No repository field.
117 warn SodaScriptIDE No README data
118 warn SodaScriptIDE No license field.
119 verbose stack Error: gui@0.5.0 postinstall: `node install.js`
119 verbose stack Exit status 1
119 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator.WIN-DKN9OK77VLJ\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
119 verbose stack     at EventEmitter.emit (events.js:182:13)
119 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator.WIN-DKN9OK77VLJ\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
119 verbose stack     at ChildProcess.emit (events.js:182:13)
119 verbose stack     at maybeClose (internal/child_process.js:961:16)
119 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
120 verbose pkgid gui@0.5.0
121 verbose cwd J:\SodaScriptIDE
122 verbose Windows_NT 6.1.7601
123 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator.WIN-DKN9OK77VLJ\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "gui"
124 verbose node v10.7.0
125 verbose npm  v6.2.0
126 error code ELIFECYCLE
127 error errno 1
128 error gui@0.5.0 postinstall: `node install.js`
128 error Exit status 1
129 error Failed at the gui@0.5.0 postinstall script.
129 error This is probably not a problem with npm. There is likely additional logging output above.
130 verbose exit [ 1, true ]

**Comment by yuu2lee4** [comment]
> gui@0.5.0 postinstall /Users/yuri/work/react-yue-app/node_modules/gui
> node install.js

Failed to download yue: Release not found: 404
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gui@0.5.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gui@0.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by yuu2lee4** [comment]
It's ok after switching my node verison to 8 from 10

**Comment by zcbenz** [comment]
Only certain Node.js versions are supported, currently you have to check https://github.com/yue/yue/releases for whether a build for a certain version of Node is available.
