### ISSUE TITLE
Rounded corners in View

### ISSUE THREAD

**Issue by roman01la** [yue/yue#65]
Does it make sense to add rounded corners rendering option to View component?

**Comment by arnold-graf** [comment]
wey (the slack client) has implemented this, if you still need it:
https://github.com/yue/wey/blob/master/lib/view/account-button.js

**Comment by zcbenz** [comment]
Only macOS provides this builtin ability and it is very limited, after some investigation I believe this is not practical to implement so I'm closing this.
