### ISSUE TITLE
Support msvc_deps_prefix in ninja

### ISSUE THREAD

**Issue by actboy168** [yue/yue#67]
https://github.com/ninja-build/ninja/blob/master/doc/manual.asciidoc

For non-English versions of msvc, ninja needs to specify msvc_deps_prefix to properly locate the depfile.

**Comment by zcbenz** [comment]
Yue uses GN to generate ninja project files, unfortunately GN does not have support  for `msvc_deps_prefix` so I can not support it in this project.
