### ISSUE TITLE
Add image view

### ISSUE THREAD

**Issue by dimitrov-adrian** [yue/yue#69]
Add Image View, so images to be added to container. Right now it's possible to use onDraw with container, but it doesn't work for nested containers.

**Comment by zcbenz** [comment]
Currently I don't have any plan to add a real image view that can cover common uses, it is recommended to use containers as image views. The `GifPlayer` is not intended to be a general image view so it is intended not to be named as ImageView.

Using `painter.drawImage` will automatically scale the image.

If there are bugs with onDraw on nested containers, please open a new issue.
