### ISSUE TITLE
Way to package the app into a single executive?

### ISSUE THREAD

**Issue by kuba-orlik** [yue/yue#7]
I really like the idea of yue, unfortunately the fact that it relies on a fork of node makes it incompatible with all the app packagers I've stumbled upon. Is there any way to turn a yue app to a simple to distribute executable?

**Comment by zcbenz** [comment]
For Node.js version I will probably integrate asar support to yode, and then add the ability to append the asar archive to executable, similar to Electron's way of doing archive.

**Comment by zcbenz** [comment]
Not the final solution, but in https://github.com/yue/muban I packaged a web app into a single executable and then loaded it in Yue's browser. I'm still thinking how to implement a full solution in yode, since many people would want to write the main app in JavaScript instead of C++.

**Comment by kuba-orlik** [comment]
Yeah, I have trouble grasping that. This code:

```
gui.MessageLoop.run();
```

is blocking, right? So how do I run asynchronous code (like an HTTP request), when the thread is blocked?

**Comment by zcbenz** [comment]
I have written https://github.com/yue/yackage to create single-executable apps.
