### ISSUE TITLE
MessageBox dialog API

### ISSUE THREAD

**Issue by dimitrov-adrian** [yue/yue#71]
Will be good to have more native messagebox dialog api, like what electron have with [dialog.showMessageBox()](https://electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options-callback), so instead of re-creating dialogs with custom icons for error, warning, ... etc. to use this api.

**Comment by zcbenz** [comment]
Closed with https://github.com/yue/yue/commit/2d418ad11bf0e4d361c4471c42fa8402fc08514b.
