### ISSUE TITLE
Irregular behavior between addrow() and removerowat()

### ISSUE THREAD

**Issue by gustavohmsilva** [yue/yue#76]
I've noticed that although in this example below, the line disappear from the table view:
```
btn_deletar.onclick = function() 
                db.delete(conexao, entry_id:gettext()) 
                tabela:removerowat(entry_id:gettext())
                conexao:commit()
        end
```
In this example, the exact opposite do not happen, the view isn't getting updated...
```
btn_cadastrar.onclick = function() 
                db.create(
                        conexao, entry_filme:gettext(), 
                        entry_produtora:gettext(), 
                        entry_ano:gettext()
                ) 
                tabela:addrow{
                        entry_filme:gettext(), 
                        entry_produtora:gettext(), 
                        entry_ano:gettext()
                }
                conexao:commit()
        end
```

Is this intentional? As the table view don't have a ```:reloadview()``` or something similar, it is my understanding the both operations, adding rows and removing them should auto reload the table view. But when creating the new row, the database receive the data OK (proving that the data is flowing ok) but the view aren't reloaded as in ```removerowat()```

**Comment by zcbenz** [comment]
This is not expected behavior, can you share which operating system are you using?

And thanks for reporting all the bugs, you are making this project better.

**Comment by gustavohmsilva** [comment]
Linux, Ubuntu 18.04.02 LTS, Gnome, proprietary driver nvidia-390, The machine is a MSI GF63 8RC.


Thanks! I'll keep doing it because the project is awesome and Lua needs a cross platform GUI asap! 

I have been using fltk, yad and Lazarus with Lua and the lack of "a single GUI that fits all my needs" is killing me :D
Yue fits all the requirements, so why not help as I can...

**Comment by gustavohmsilva** [comment]
@zcbenz, this is the complete source code of the application I've been testing Yue in, hope it helps:   
https://github.com/gustavohmsilva/filmografia

**Comment by zcbenz** [comment]
I'm trying to reproduce the problem with a simple app but it worked fine, can you try if it works fine on your machine?

```lua
local gui = require('yue.gui')

local win = gui.Window.create{}
win:setcontentsize{width=240, height=120}

function win.onclose()
  gui.MessageLoop.quit()
end

local contentView = gui.Container.create()
win:setcontentview(contentView)

local add = gui.Button.create('Add')
contentView:addchildview(add)

local table = gui.Table.create()
table:setstyle{flex=1}
table:addcolumn('Column')
local model = gui.SimpleTableModel.create(1)
table:setmodel(model)
contentView:addchildview(table)

function add.onclick()
  model:addrow{'123'}
end

win:center()
win:activate()

gui.MessageLoop.run()
```

**Comment by gustavohmsilva** [comment]
Weird. In your code the behavior is the expected outcome. Could you run my repo on your machine, just in case? 

The differences between ours consist basically on the fact that your example is only one window, while mine has multiple.

**Comment by zcbenz** [comment]
Your code does not work because it creates a model with 4 columns but only adds row with 3 items.

I'll make the error more verbose in Yue.
