### ISSUE TITLE
Create Font-Object from file

### ISSUE THREAD

**Issue by Skayo** [yue/yue#77]
Is it possible to create a Font Object from a font file (for example .ttf) ?
In the docs I only see a name parameter, not a path parameter.
So I guess you can only use system fonts?

**Comment by J-Cake** [comment]
just came across this too, I guess you'd have to use a third party library to parse the font file, somehow convert it into Yue's font system and try to connect them.

**Comment by zcbenz** [comment]
Closed with https://github.com/yue/yue/commit/4509b7be61d93b05aae1b814f3038ed6dc876700.
