### ISSUE TITLE
How to open devTools of a Browser Object?

### ISSUE THREAD

**Issue by Skayo** [yue/yue#78]
Question in the title. How do I do that? There's an option for Browser named "devTools", which you can enable. But what does it do? Where are the devTools?

**Comment by lb091188** [comment]
> Currently this option is not working on Windows.

**Comment by zcbenz** [comment]
Unfortunately the APIs provided by Windows do not have any ability to open devtools, it might be possible after we add support for the new WebView2 APIs (https://github.com/yue/yue/issues/91).
