### ISSUE TITLE
OCaml bindings?

### ISSUE THREAD

**Issue by hackwaly** [yue/yue#81]
作者你好，

你看过 https://github.com/revery-ui/revery 和 https://github.com/briskml/brisk 吗？
这两个库是ocaml/reason的，随着facebook的推动，reason变得越来越流行。使用ocaml/reason也有很多显而易见的好处（相比lua和js），比如说static type、pattern match、persistent data structure、jsx等等，还有native级别的性能。是否有可能yue提供ocaml的bindings？

**Comment by zcbenz** [comment]
OCaml我实在不熟，这个没有打算支持的。
