### ISSUE TITLE
ComboBox inherits ComboBox? 😅

### ISSUE THREAD

**Issue by dimitarnestorov** [yue/yue#83]
Did you mean Picker?
https://libyue.com/docs/v0.6.3/js/api/combobox.html
![image](https://user-images.githubusercontent.com/8790386/57465820-11b98380-7288-11e9-9968-8009e5cbefa6.png)

Also you should pin this repository in the organization.

**Comment by zcbenz** [comment]
Thanks for noticing this, closed with 56e8b9b.
