### ISSUE TITLE
icons for menuitems and windows

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [yue/yue#86]
I didn't find any references in the documentation.
Is this planned to be implemented?

**Comment by zcbenz** [comment]
It is not supported yet, I will implement it but there is no estimation on when.

**Comment by zcbenz** [comment]
Closed with f2691479b16c96c4f972acbb1f3c14f5e1b5102e and 2bead5104113f21b9c39ee0f75dcc01759900dd6.

**Comment by 0x4E69676874466F78** [comment]
Thanks!
