### ISSUE TITLE
Webview 2 on Windows?

### ISSUE THREAD

**Issue by Losses** [yue/yue#91]
Is it possible to use Webview 2 on Windows if it's available?

**Comment by zcbenz** [comment]
Looking at the APIs I think it is totally doable.

**Comment by zcbenz** [comment]
Support has been added in v0.8.5.

**Comment by RGdevz** [comment]
Hello, is there a way to use RegisterProtocol on webview2? I see it only works on ie

**Comment by zcbenz** [comment]
It is currently not supported, but it seems that WebView2 has added support for custom scheme 2 years ago: https://github.com/MicrosoftEdge/WebView2Feedback/pull/2288, so this feature should be possible to implement now.

**Comment by zcbenz** [comment]
@RGdevz Fixed with https://github.com/yue/yue/commit/e6ed7c262ba2ac881b6e433cf54a52b80cd1a1a2.

**Comment by RGdevz** [comment]
Very cool! Thanks for adding this
