### ISSUE TITLE
Add support for dark mode

### ISSUE THREAD

**Issue by mdings** [yue/yue#94]
While more apps are supporting dark mode for their UIs it seems like a good idea to bring this to Yue too. I specifically like the way Electron is handling this by providing a subscriber (see below). The upside of this is that we are also able to subscribe to different notifications, like when the user has locked/unlocked his screen etc.

What do you think?

```
const { systemPreferences } = require('electron')

systemPreferences.subscribeNotification(
  'AppleInterfaceThemeChangedNotification',
  function theThemeHasChanged () {
    updateMyAppTheme(systemPreferences.isDarkMode())
  }
)
```

**Comment by zcbenz** [comment]
Closed with 3a9ff960533407e6103be8fa4576de0cefa4b3b7.
